# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20171119_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
