# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20171121_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='location',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.User'),
        ),
    ]
