# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20171206_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
