# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171117_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
