# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='location',
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
